[versions]
android-gradle-plugin = "7.3.0"  # Use the latest version suitable for your project
kotlin = "1.8.0"                # Use the latest Kotlin version
navigation = "2.5.1"
appcompat = "1.6.1"
material = "1.12.0"
constraintlayout = "2.1.4"  # This should be the latest version of the Navigation library
[plugins]
androidApplication = { id = "com.android.application", version.ref = "android-gradle-plugin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
